# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://ubermenchh.github.io',
                'git_url': 'https://github.com/ubermenchh/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.training': { 'miniai.training.Dataset': ('minibatch_training.html#dataset', 'miniai/training.py'),
                                 'miniai.training.Dataset.__getitem__': ( 'minibatch_training.html#dataset.__getitem__',
                                                                          'miniai/training.py'),
                                 'miniai.training.Dataset.__init__': ('minibatch_training.html#dataset.__init__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__len__': ('minibatch_training.html#dataset.__len__', 'miniai/training.py'),
                                 'miniai.training.accuracy': ('minibatch_training.html#accuracy', 'miniai/training.py'),
                                 'miniai.training.fit': ('minibatch_training.html#fit', 'miniai/training.py'),
                                 'miniai.training.get_dls': ('minibatch_training.html#get_dls', 'miniai/training.py'),
                                 'miniai.training.report': ('minibatch_training.html#report', 'miniai/training.py')}}}
